name: cv_for_khamidjon
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # util
  encrypt: ^5.0.1
  supercharged: ^2.1.1
  logger: ^1.1.0
  equatable: ^2.0.3

  # ui
  flutter_screenutil: ^5.0.0+2
  pull_to_refresh: ^2.0.0
  google_fonts: ^2.1.0

  #animation
  flutter_animation_progress_bar: ^2.0.1
  animated_text_kit: ^4.2.1
  animated_widgets: ^1.1.0

  # bloc
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  rxdart: ^0.27.2

  #database
  sembast: ^3.1.1

  # path provider
  path_provider: ^2.0.7
  path: ^1.8.0
  shared_preferences: ^2.0.8
  permission_handler: ^8.3.0
  share_plus: ^3.0.4

  #network
  dio: ^4.0.3
  connectivity_plus: ^2.0.3
  url_launcher: ^6.0.13
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1

  #image
  cached_network_image: ^3.1.0+1
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  build_runner: ^2.1.5

# flutter pub run build_runner build -> generates json files
#  very_good_analysis: ^2.4.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/menu_images/
    - assets/experience_icons/

flutter_intl:
  enabled: true
